### ISSUE TITLE
Even lazier instantiation of event listeners?

### ISSUE THREAD

**Issue by Pittiplatsch** [zendframework/zend-eventmanager#61]
Hey folks,

while deeply diving into event manager and its performance, I wonder if even lazier instantiation of event listeners at the last possible moment, i.e. ``\Zend\EventManager\EventManager::triggerListeners()`` could further improve performance?
I realize LazyListeners already exist, but they are usually instantiated during instantiation of the respective event manager.
In case of many events for the same event manager this obviously leads to many unnecessary operations.

Any opions?

**Comment by nuxwin** [comment]
@Pittiplatsch 

As far as I known, Lazy event listeners were implemented in ZF3.

See https://zendframework.github.io/zend-eventmanager/lazy-listeners/lazy-listener/#lazylistener

I don't known much about implementation details since I'm still on ZF2.. I think that they implemented them using virtual proxy pattern but I'm not sure.

**Comment by Pittiplatsch** [comment]
As I stated, I do know LazyListeners.
My point is that I see even more potential for increasing performance by avoiding premature instantiation of **any** listener objects, even lazy listener objects.
Or did I miss something?

**Comment by nuxwin** [comment]
@Pittiplatsch 

The purpose of a lazy event listener is to instantiate the real event listener when the event on which it is listening is triggered. This is a real performance gain because the "wrapped" event listener will not be instantiated on registration. Registering a lazy event listener in place of a real event listener is really cheap. Think that a real event listener can requires configuration phase and so on... leading to useless works when finally, no events on which it is listening is triggered. In any cases, the event listener must be registered, else, the event manager will not be aware of it.

Note that this is my understanding of lazy listeners  (assumptions). I may be wrong at some points because I never used them yet.

@weierophinney or @Ocramius Can you confirm?

**Comment by Pittiplatsch** [comment]
Well, I see that Lazy Listeners can be very cheap compared to potentially expensive, but needless instantiation of the "real" wrapped event listener.

However, I want to point out that even the cheapest instantiation of (a potentially substantial set of) lazy listeners which at least do some consistency / validation checks of given definition is by far more expensive than delaying **any** instantiation to the last possible moment which is just at the time of triggering the respective event.

Granted, the event name must be evaluated in either case, but building a simple data structure in analogy to ``\Zend\EventManager\EventManager::$events`` is obviously cheaper than instantiating any object at all.

**Comment by Ocramius** [comment]
Object instantiation is still cheaper than inventing a new data structure
that adds a layer of indirection. What is possibly heavy is the related
autoloading, but not really the instantiation.

I strongly suggest writing benchmarks for the scenario before bringing the
proposal any further.

**Comment by Pittiplatsch** [comment]
👍 for writing benchmarks first.

I must admit that I don't really know how to start doing so...
I don't see how to benchmark two different EM implemenations against each other using current benchmark architecture (https://github.com/zendframework/zend-eventmanager/tree/master/benchmarks).

Could plz someone shed some light?

**Comment by Ocramius** [comment]
@Pittiplatsch argh, these benchmarks are still using athletic. We should port them to [phpbench](https://github.com/phpbench/phpbench), which has export/comparison utilities (see https://github.com/doctrine/doctrine2/pull/6649#issuecomment-325133806 for an example of what this looks like)

**Comment by Pittiplatsch** [comment]
Phew, that's definitely out of this issue's scope...
Not sure how to proceed from here :confused:

**Comment by Ocramius** [comment]
1. let's move to phpbench (separate issue)
 2. continue here after that

**Comment by michalbundyra** [comment]
@Ocramius @Pittiplatsch I can move it to phpbench :) I'll push my PR soon.

**Comment by michalbundyra** [comment]
Switched to phpbench in PR #62

**Comment by weierophinney** [comment]
@Pittiplatsch You've made a ton of assertions that things can be made faster... but not exactly how, nor what the trade-offs might be.

As @Ocramius noted, we definitely need benchmarks so that we can compare, and I see that @webimpress has opened a pull request to update to phpbench, which will allow that.

Next, however, is how you would plan to _implement_ such changes. A lot of thought went into the design for zend-eventmanager v3, and one aspect in particular was _type safety_. Being able to provide a specific _type_ when attaching listeners greatly reduces the internal complexity as we now no longer need to determine what we received, nor, at execution of listeners, determine if we need to marshal something before we execute it.

Lazy listeners were a key aspect of that: by having a lightweight object that composes the service name and the DI container, we are essentially only storing _references_ until the listener is executed. This delays creation and greatly conserves resources.

Yes, we have an actual object in the scope, but as @Ocramius notes, this is a cheap operation in modern PHP versions.

So, we'll be weighing several factors as you provide a proposal:

- Performance
- Resource overhead
- Code complexity

Please keep these in mind as you proceed, and I look forward to seeing your experiments, regardless of their outcomes!

**Comment by Pittiplatsch** [comment]
Very rough draft:
https://github.com/Pittiplatsch/zend-eventmanager/commit/8611005872d65c57642eed403acbe52cd45025fb

I think, comparison should be done based on ``\ZendBench\EventManager\MultipleEventListenerDefinitionBench`` vs. ``\ZendBench\EventManager\MultipleEventLocalListenerBench`` (the original benchmark that I simply copied and adjusted).

If I read the benchmark results correctly (``vendor/bin/phpbench run benchmarks/ --iterations=100 --revs=100 --filter MultipleEventLocal --filter MultipleEventListener``), my version seems to be notably slower.

However, my local tests which directly compare usage of ``\Zend\EventManager\LazyListenerAggregate`` against my "even lazier listener" version prove that time for attaching listeners is reduced by >50%, and even actual triggering is saves ~30%.

Therefore, I am not sure if I may trust my rude benchmark test...

@weierophinney Thx for your enlightenment. I definitly see my code will increase complexity, especially the part with "kind of self-modifying code" of the wrapper listener.
From that point of view I'd absolutely accept if my approach didn't find your agreement.

Anyhow, any comments are welcome 😄 

--
Edit:
I just saw that my benchmark is extremly naive and unrealistic as it just attaches a listener and immediately triggers the respective event.
Seems that I have to clone the other benchmarks as well to obtain a realistic result.

**Comment by Ocramius** [comment]
Remember to run the benchmark without XDebug

**Comment by Pittiplatsch** [comment]
>  Remember to run the benchmark without XDebug

Thx for that. Absolute times went massively down, but the relative result stays within similar ranges.

**Comment by Pittiplatsch** [comment]
After @weierophinney 's notes, is my approach worth any further work?
It obviously contradicts current implementation's simplicity and type safety.
By now I can't imagine a compromise of my approach vs. current implemenation as my approach gains its speed from its admitted dirtiness :smirk:

Otherwise, I'm fine with just closing this issue.

**Comment by Ocramius** [comment]
Close it and reopen once you have a better plan of attack.
