### ISSUE TITLE
Explore the option of use event class FQCN (::class) as event name

### ISSUE THREAD

**Issue by Maks3w** [zendframework/zend-eventmanager#7]
Use the FQCN of an event name make easy to provide unique event names and avoid name conflicts between libraries.

Pro:
- FQCN + PHP 5.5 class makes almost imposible mistakes in event name (typos while typing the event name string) and PHP error message is enough for to determinate error nature and location.
- Does not require `getName` neither `getTarget` on EventInterface
- `SharedEventManager` could be removed.

Con:
- Need to compare large strings while filtering the listeners. Anyone knows if PHP it's enough smart for compare two strings by the same memory reference?
- Require to have 1 class per event.
- Makes more difficult wildcard events (could require substring matches)

**Comment by danizord** [comment]
> FQCN + PHP 5.5 class makes almost imposible mistakes in event name (typos while typing the event name string) and PHP error message is enough for to determinate error nature and location.

PHP does not produce error messages for `Non\Existent\ClassName::class`

Anyway, completely :+1:

**Comment by weierophinney** [comment]
This would make it impossible to trigger multiple events from a single class, which is completely against the design of the component, and would break many important use cases that already exist _in the framework_. (We trigger multiple events in `Zend\Mvc\Application`!!!) As such, a BIG :-1:, and I don't think we should consider this at all.

**Comment by Maks3w** [comment]
Today I've refactor all trigger uses of scalar values `trigger(evenName, target, params)` with EventInterface classes.

And the code is more readable than before.

I've to admit I didn't yet create 1 class per event but seems to be the next refactor I'll do (some day).

One option of use the FQCN is any object can be an event payload. There is no need to implement `EventInterface`

**Comment by weierophinney** [comment]
This is certainly an approach you can adopt on a per-case basis. However, we have many places in the MVC and elsewhere with classes that trigger _multiple_ events, often based on either which method is invoked, or in order to create a workflow. Limiting event names to _only_ the class name limits the number of events triggered to exactly one.

Regarding this statement:

> FQCN + PHP 5.5 class makes almost imposible mistakes in event name (typos while typing the event name string) and PHP error message is enough for to determinate error nature and location.
> PHP does not produce error messages for Non\Existent\ClassName::class

You get similar benefits by using `__FUNCTION__` or `__METHOD__`; the latter can be used if you want to rely on your IDE's autocompletion. Both of these have the benefit of allowing more granularity than the class name alone.
