### ISSUE TITLE
Package container-interop is abandoned

### ISSUE THREAD

**Issue by TWithers** [zendframework/zend-eventmanager#79]
Did a fresh install of a project with zend-soap, which requires zend-eventmanager, which requires container-interop/container-interop.

Composer is throwing the following warning:

`Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.`

**Comment by weierophinney** [comment]
This is due to container-interop marking their packages as abandoned.

Please note that "abandoned" does not mean "uninstallable". It means that there will be no future updates to the package. Which makes perfect sense here, as PSR-11 was ratified, superceding it.

Unfortunately, updating the various ZF packages requires updating zend-servicemanager, and we cannot change it until its next major version, as doing so now would be a BC break. While the interfaces are equivalent, and container-interop versions we pin to extend PSR-11, the problem is that the inheritance trees would break.

We are definitely aware of the issue (I myself voted for container-interop to deprecate and abandon its packages), but please be aware that (a) we know about the issue, and will resolve it eventually, and (b) it will not affect your application installs, and you can continue using the packages normally.
